# Generated by Django 5.0.6 on 2024-08-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='show_date',
            field=models.DateField(null=True),
        ),
    ]
