# Generated by Django 5.0.6 on 2024-08-10 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0002_alter_recipes_show_date'),
        ('Story', '0003_storycomment_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_category', to='Story.category'),
        ),
    ]
