# Generated by Django 5.0.6 on 2024-08-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
