# Generated by Django 5.0.6 on 2024-07-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_alter_slider_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='slider-image/'),
        ),
    ]
