# Generated by Django 5.0.6 on 2024-09-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_alter_subscriber_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='title_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
