# Generated by Django 5.0.6 on 2024-07-26 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Story', '0002_storycomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='storycomment',
            name='story',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Story.story'),
            preserve_default=False,
        ),
    ]
