# Generated by Django 5.0.6 on 2024-09-30 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_basket_basketitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_items', to='Order.basket'),
        ),
    ]
