# Generated by Django 5.0.6 on 2024-09-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_alter_basketitem_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
